### ISSUE TITLE
Error in looping logic for skeletons with unequal number of bones

### ISSUE THREAD

**Issue by thefortyseventh** [Pentalimbed/hkxmerge#1]
Hi,

I noticed some serious problems when working with animations with different number of bones for each skeleton (i.e. paired_mount.hkx).

I believe that at least partially, this is due to line 92 in merger.cpp:
anno_tracks[anim_a->m_numberOfTransformTracks + 2].m_trackName = "NPC";

which should be:
 anno_tracks[anim_v->m_numberOfTransformTracks + 2].m_trackName = "NPC";

in order to count 2 beyond the "victim" skeleton. Right now, you end up with "NPC" in the middle of one of the skeleton's, overwriting one of their bone annotations, and a blank &#9216; where "NPC" should be.

I don't know if it actually breaks the animation as I don't know how havok actually does its transforms.

**Comment by Pentalimbed** [comment]
Thank you for the response. Did you test the change yourself and did it work?

**Comment by T4T7TH** [comment]
Sorry lost my login!
Yes, this change works perfectly as far as I can tell, thanks for the great tool!
